In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import datetime as dt

In [7]:
dt.datetime.strptime('2020-05-12',"%Y-%m-%d")

datetime.datetime(2020, 5, 12, 0, 0)

In [8]:
dt.datetime.strftime(dt.date(2020,5,4),'%Y/%m/%d')

'2020/05/04'

In [10]:
pd.Timestamp('2020-5-8')

Timestamp('2020-05-08 00:00:00')

In [11]:
pd.Timestamp(dt.datetime(2020,5,4))

Timestamp('2020-05-04 00:00:00')

In [17]:
ts =pd.Timestamp('3rd of april 2020')
ts

Timestamp('2020-04-03 00:00:00')

In [18]:
ts.month

4

In [19]:
ts.is_leap_year

True

In [20]:
ts.quarter

2

# datetime index

In [21]:
date = [pd.Timestamp('2020/5/12'),pd.Timestamp('2025/5/12'),
        pd.Timestamp('2024/5/12')]
date

[Timestamp('2020-05-12 00:00:00'),
 Timestamp('2025-05-12 00:00:00'),
 Timestamp('2024-05-12 00:00:00')]

In [23]:
ts = pd.Series(np.random.randn(3),date)
ts

2020-05-12    1.231952
2025-05-12    0.323957
2024-05-12    1.244011
dtype: float64

In [24]:
ts.index

DatetimeIndex(['2020-05-12', '2025-05-12', '2024-05-12'], dtype='datetime64[ns]', freq=None)

In [35]:
df = pd.read_csv(R"dataset/Tweets.csv")

In [36]:
df= pd.read_excel(R"dataset/new_TWTR.xlsx")

In [37]:
df.head(5)

,Unnamed: 0,Date,Open,High,Low,Close,Adj Close,Volume
0,0,2013-12-09,45.590000,49.840000,45.020000,49.139999,49.139999,17366614
1,1,2013-12-10,48.900002,52.580002,48.700001,51.990002,51.990002,25792002
2,2,2013-12-11,52.400002,53.869999,51.000000,52.340000,52.340000,26631535
3,3,2013-12-12,52.200001,55.869999,50.689999,55.330002,55.330002,23446870
4,4,2013-12-13,56.200001,59.410000,55.450001,59.000000,59.000000,38979567

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2238 entries, 0 to 2237
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2238 non-null   int64
 1   Date        2238 non-null   object
 2   Open        2238 non-null   float64
 3   High        2238 non-null   float64
 4   Low         2238 non-null   float64
 5   Close       2238 non-null   float64
 6   Adj Close   2238 non-null   float64
 7   Volume      2238 non-null   int64
dtypes: float64(5), int64(2), object(1)
memory usage: 140.0+ KB

In [16]:
#df['Date'] = df['Date'].astype(np.datetime64)
df['Date']=pd.to_datetime(df['Date'])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2238 entries, 0 to 2237
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2238 non-null   int64
 1   Date        2238 non-null   datetime64[ns]
 2   Open        2238 non-null   float64
 3   High        2238 non-null   float64
 4   Low         2238 non-null   float64
 5   Close       2238 non-null   float64
 6   Adj Close   2238 non-null   float64
 7   Volume      2238 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(2)
memory usage: 140.0 KB

In [18]:
df.set_index('Date',inplace=True)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2238 entries, 2013-12-09 to 2022-10-27
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2238 non-null   int64
 1   Open        2238 non-null   float64
 2   High        2238 non-null   float64
 3   Low         2238 non-null   float64
 4   Close       2238 non-null   float64
 5   Adj Close   2238 non-null   float64
 6   Volume      2238 non-null   int64
dtypes: float64(5), int64(2)
memory usage: 139.9 KB

In [33]:
df.head()

,Unnamed: 0,Open,High,Low,Close,Adj Close,Volume,year,month,day,day_name
Date,,,,,,,,,,,
2013-12-09,0,45.590000,49.840000,45.020000,49.139999,49.139999,17366614,2013,12,9,Monday
2013-12-10,1,48.900002,52.580002,48.700001,51.990002,51.990002,25792002,2013,12,10,Tuesday
2013-12-11,2,52.400002,53.869999,51.000000,52.340000,52.340000,26631535,2013,12,11,Wednesday
2013-12-12,3,52.200001,55.869999,50.689999,55.330002,55.330002,23446870,2013,12,12,Thursday
2013-12-13,4,56.200001,59.410000,55.450001,59.000000,59.000000,38979567,2013,12,13,Friday

In [32]:
df['year'] =df.index.year
df['month'] =df.index.month
df['day'] =df.index.day
df['day_name'] =df.index.day_name()

In [35]:
df.groupby('day_name').mean()

,Unnamed: 0,Open,High,Low,Close,Adj Close,Volume,year,month,day
day_name,,,,,,,,,,
Friday,1118.493274,35.902859,36.495034,35.254239,35.850247,35.850247,2.089129e+07,2017.883408,6.482063,15.816143
Monday,1113.890476,36.003946,36.654310,35.282621,35.973857,35.973857,2.159552e+07,2017.854762,6.664286,15.723810
Thursday,1122.116998,36.033412,36.737380,35.365260,36.026622,36.026622,2.317605e+07,2017.907285,6.388521,15.664459
Tuesday,1116.900217,36.004365,36.729311,35.328356,36.005900,36.005900,2.127057e+07,2017.880694,6.481562,15.798265
Wednesday,1120.766376,35.864901,36.560829,35.195043,35.867773,35.867773,2.212635e+07,2017.897380,6.451965,15.781659

### dealing with datetime when import data

In [54]:
df = pd.read_excel('dataset/new_TWTR.xlsx',parse_dates=['Date']) # index_col=['Date'] as set_index

In [58]:
df =df.set_index('Date')

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2238 entries, 2013-12-09 to 2022-10-27
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2238 non-null   int64
 1   Open        2238 non-null   float64
 2   High        2238 non-null   float64
 3   Low         2238 non-null   float64
 4   Close       2238 non-null   float64
 5   Adj Close   2238 non-null   float64
 6   Volume      2238 non-null   int64
dtypes: float64(5), int64(2)
memory usage: 139.9 KB

In [3]:
df = pd.read_excel('dataset/new_TWTR.xlsx') # index_col=['Date'] as set_index

In [4]:
df = df.set_index(pd.to_datetime(df['Date'])).drop('Date',axis=1)

In [87]:
df.head()

,Unnamed: 0,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,,
2013-12-09,0,45.590000,49.840000,45.020000,49.139999,49.139999,17366614
2013-12-10,1,48.900002,52.580002,48.700001,51.990002,51.990002,25792002
2013-12-11,2,52.400002,53.869999,51.000000,52.340000,52.340000,26631535
2013-12-12,3,52.200001,55.869999,50.689999,55.330002,55.330002,23446870
2013-12-13,4,56.200001,59.410000,55.450001,59.000000,59.000000,38979567

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2238 entries, 2013-12-09 to 2022-10-27
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2238 non-null   int64
 1   Open        2238 non-null   float64
 2   High        2238 non-null   float64
 3   Low         2238 non-null   float64
 4   Close       2238 non-null   float64
 5   Adj Close   2238 non-null   float64
 6   Volume      2238 non-null   int64
dtypes: float64(5), int64(2)
memory usage: 139.9 KB

In [5]:
df=df[['Open','Close']]

In [6]:
df.head()

                 Open      Close
Date
2013-12-09  45.590000  49.139999
2013-12-10  48.900002  51.990002
2013-12-11  52.400002  52.340000
2013-12-12  52.200001  55.330002
2013-12-13  56.200001  59.000000

### index , slicling

In [95]:
df.iloc[0:1]

             Open      Close
Date
2013-12-09  45.59  49.139999

In [113]:
st=df.loc['2014-1'] # for hour 01:00:00
en =df.loc['2014-4'] # for hour 01:00:00

In [119]:
st =dt.datetime(2011,1,1)
en=dt.datetime(2011,4,30)

In [120]:
index =pd.date_range(st,en)

In [121]:
index

DatetimeIndex(['2011-01-01', '2011-01-02', '2011-01-03', '2011-01-04',
               '2011-01-05', '2011-01-06', '2011-01-07', '2011-01-08',
               '2011-01-09', '2011-01-10',
               ...
               '2011-04-21', '2011-04-22', '2011-04-23', '2011-04-24',
               '2011-04-25', '2011-04-26', '2011-04-27', '2011-04-28',
               '2011-04-29', '2011-04-30'],
              dtype='datetime64[ns]', length=120, freq='D')

In [122]:
ts =pd.Series(np.random.randn(len(index)),index=index)

In [125]:
ts

2011-01-01    1.126936
2011-01-02    0.018122
2011-01-03   -0.152613
2011-01-04    2.466925
2011-01-05    1.544318
                ...
2011-04-26    0.715240
2011-04-27    2.048677
2011-04-28    0.970463
2011-04-29   -1.079326
2011-04-30    0.312034
Freq: D, Length: 120, dtype: float64

In [126]:
ts = pd.Timestamp('2020-7-22')

In [128]:
ts - pd.DateOffset(days=10)

Timestamp('2020-07-12 00:00:00')

In [130]:
df.head()

                 Open      Close
Date
2013-12-09  45.590000  49.139999
2013-12-10  48.900002  51.990002
2013-12-11  52.400002  52.340000
2013-12-12  52.200001  55.330002
2013-12-13  56.200001  59.000000

In [131]:
df.set_index(df.index+pd.DateOffset(minutes=30))

                          Open      Close
Date
2013-12-09 00:30:00  45.590000  49.139999
2013-12-10 00:30:00  48.900002  51.990002
2013-12-11 00:30:00  52.400002  52.340000
2013-12-12 00:30:00  52.200001  55.330002
2013-12-13 00:30:00  56.200001  59.000000
...                        ...        ...
2022-10-21 00:30:00  50.000000  49.889999
2022-10-24 00:30:00  50.709999  51.520000
2022-10-25 00:30:00  52.415001  52.779999
2022-10-26 00:30:00  52.950001  53.349998
2022-10-27 00:30:00  53.910000  53.700001

[2238 rows x 2 columns]

### resmpling time series

Open     0
Close    0
dtype: int64

In [20]:
df.resample('Y').mean()

                 Open      Close
Date
2013-12-31  58.281875  59.349375
2014-12-31  45.614901  45.451508
2015-12-31  35.408611  35.344325
2016-12-31  17.573532  17.571111
2017-12-31  17.804694  17.823506
2018-12-31  32.830210  32.828526
2019-12-31  35.580129  35.575476
2020-12-31  37.161560  37.215771
2021-12-31  60.111216  59.991746
2022-12-31  40.952585  41.034783

In [21]:
rng = pd.date_range('1/1/2020',periods=4,freq='T')
series = pd.Series([0.0,None,2.0,3.0],index=rng)
df=pd.DataFrame({'s':series})

In [22]:
df

                       s
2020-01-01 00:00:00  0.0
2020-01-01 00:01:00  NaN
2020-01-01 00:02:00  2.0
2020-01-01 00:03:00  3.0

In [40]:
df = pd.read_csv('dataset/BrentOilPrices.csv')

In [51]:
df.head()

            Price
Date
1987-05-20  18.63
1987-05-21  18.45
1987-05-22  18.55
1987-05-25  18.60
1987-05-26  18.63

In [42]:
df['Date']=pd.to_datetime(df['Date'])

C:\Users\G.B\AppData\Local\Temp\ipykernel_15532\772075079.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date']=pd.to_datetime(df['Date'])

In [50]:
df.set_index(df['Date'],inplace=True)
df =df.drop('Date',axis=1)